version: "3.8"

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "denoserver"
      MYSQL_ROOT_PASSWORD: Chofiisjo80@MAC
  api:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/usr/app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db # this should be identical to the database service name
      - DB_USER=root
      - DB_DATABASE=denoserver
      - DB_PASSWORD=Chofiisjo80@MAC
      - TOKEN_SECRET=ThisIsASecretToken@80
